# fly.toml app configuration file generated for recipesimply-frontend on 2026-04-04T10:39:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "recipesimply"
primary_region = "ord"

[processes]
  app = "bash /app/entrypoint.sh"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "get"
    path = "/"

[deploy]
  strategy = "immediate"

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "RecipeSimply.settings.prod"
  PORT = "8000"
