import os
from .base import ALLOWED_HOSTS as ALLOWED_HOSTS, ASGI_APPLICATION as ASGI_APPLICATION, BASE_DIR as BASE_DIR, CORS_ALLOWED_ORIGINS as CORS_ALLOWED_ORIGINS, CSRF_TRUSTED_ORIGINS as CSRF_TRUSTED_ORIGINS, DATABASES as DATABASES, DEBUG as DEBUG, INSTALLED_APPS as INSTALLED_APPS, MEDIA_ROOT as MEDIA_ROOT, MEDIA_URL as MEDIA_URL, MIDDLEWARE as MIDDLEWARE, NAME as NAME, Path as Path, ROOT_URLCONF as ROOT_URLCONF, SECRET_KEY as SECRET_KEY, STATIC_ROOT as STATIC_ROOT, STATIC_URL as STATIC_URL, TEMPLATES as TEMPLATES, WSGI_APPLICATION as WSGI_APPLICATION, dj_database_url as dj_database_url, env as env, environ as environ, os as os

import os
from .base import *

DEBUG = False

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_REDIRECT_EXEMPT = [r"^health/$"]

TEMPLATES[0]['DIRS'] = [
    os.path.join(BASE_DIR, 'RecipeSimply', 'templates')
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
