from .base import ALLOWED_HOSTS as ALLOWED_HOSTS, ASGI_APPLICATION as ASGI_APPLICATION, BASE_DIR as BASE_DIR, CORS_ALLOWED_ORIGINS as CORS_ALLOWED_ORIGINS, DATABASES as DATABASES, DEBUG as DEBUG, INSTALLED_APPS as INSTALLED_APPS, MEDIA_ROOT as MEDIA_ROOT, MEDIA_URL as MEDIA_URL, MIDDLEWARE as MIDDLEWARE, Path as Path, ROOT_URLCONF as ROOT_URLCONF, SECRET_KEY as SECRET_KEY, STATIC_ROOT as STATIC_ROOT, STATIC_URL as STATIC_URL, TEMPLATES as TEMPLATES, WSGI_APPLICATION as WSGI_APPLICATION, env as env, environ as environ, os as os
import os

DEBUG = False

DATABASES["default"].update({
    "NAME": os.getenv("MYSQL_DB"),
    "USER": os.getenv("MYSQL_USER"),
    "PASSWORD": os.getenv("MYSQL_PASSWORD"),
    "HOST": os.getenv("MYSQL_HOST"),
    "PORT": os.getenv("MYSQL_PORT", "3306"),
})
